In [23]:
import pandas as pd
import numpy as np

In [24]:
data = [
    [2001, 'C101', '2023-08-01 18:00', '2023-08-01 18:45', 500, 'upi', 'Dominos', 4],
    [2002, 'C102', '2023-08-01 19:00', '2023-08-01 18:50', 700, 'Credit card', 'KFC', 5],
    [2003, 'C103', '2023/08/02 20:00', np.nan, np.nan, 'Debit Card', 'McDonalds', 3],
    [2004, 'C104', 'invalid', '2023-08-03 21:00', 800, 'UPI', 'Dominos', 6],
    [2005, 'C105', '2023-08-04 18:30', '2023-08-04 19:00', -200, 'Cash', 'KFC', 2],
    [2005, 'C105', '2023-08-04 18:30', '2023-08-04 19:00', -200, 'Cash', 'KFC', 2],
    [2006, 'C106', '2023-08-05 17:00', '2023-08-05 17:40', 1200, '', 'Pizza Hut', 4],
]

columns = ['order_id', 'customer_id', 'order_time', 'delivery_time', 'order_value', 'payment_method', 'restaurant', 'rating']

df = pd.DataFrame(data, columns=columns)

df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00,2023-08-01 18:45,500.0,upi,Dominos,4
1,2002,C102,2023-08-01 19:00,2023-08-01 18:50,700.0,Credit card,KFC,5
2,2003,C103,2023/08/02 20:00,NaN,NaN,Debit Card,McDonalds,3
3,2004,C104,invalid,2023-08-03 21:00,800.0,UPI,Dominos,6
4,2005,C105,2023-08-04 18:30,2023-08-04 19:00,-200.0,Cash,KFC,2
5,2005,C105,2023-08-04 18:30,2023-08-04 19:00,-200.0,Cash,KFC,2
6,2006,C106,2023-08-05 17:00,2023-08-05 17:40,1200.0,,Pizza Hut,4

In [25]:
df['order_time'] = pd.to_datetime(df['order_time'], errors='coerce')
df['delivery_time'] = pd.to_datetime(df['delivery_time'], errors='coerce')

In [26]:
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,upi,Dominos,4
1,2002,C102,2023-08-01 19:00:00,2023-08-01 18:50:00,700.0,Credit card,KFC,5
2,2003,C103,NaT,NaT,NaN,Debit Card,McDonalds,3
3,2004,C104,NaT,2023-08-03 21:00:00,800.0,UPI,Dominos,6
4,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
5,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,,Pizza Hut,4

In [27]:
df = df.dropna(subset=['order_time', 'delivery_time'])

In [28]:
df = df[df['delivery_time'] >= df['order_time']]

In [29]:
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,upi,Dominos,4
4,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
5,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,,Pizza Hut,4

In [30]:
df = df[df['order_value'] > 0]

In [31]:
df = df[(df['rating'] >= 1) & (df['rating'] <= 5)]

In [32]:
df['payment_method'] = df['payment_method'].str.lower().str.strip()

df['payment_method'] = df['payment_method'].replace({
    'upi': 'UPI',
    'credit card': 'Credit Card',
    'debit card': 'Debit Card',
    'cash': 'Cash',
    '': 'Unknown'
})

In [33]:
df.reset_index(drop=True, inplace=True)
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,UPI,Dominos,4
1,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,Unknown,Pizza Hut,4